export const _PENDING = '_PENDING'
export const ADD_PROPOSAL_VOTE = 'ADD_PROPOSAL_VOTE'
export const ADD_PROPOSAL_VOTE_PENDING = 'ADD_PROPOSAL_VOTE' + _PENDING
export const BLOCK_USER = 'BLOCK_USER'
export const CLEAR_MODERATOR_SUGGESTIONS = 'CLEAR_MODERATOR_SUGGESTIONS'
export const CLEAR_MODERATION_ACTION = 'CLEAR_MODERATION_ACTION'
export const CLEAR_MODERATION_ACTION_PENDING = 'CLEAR_MODERATION_ACTION' + _PENDING
export const CREATE_MODERATION_ACTION = 'CREATE_MODERATION_ACTION'
export const CREATE_MODERATION_ACTION_PENDING = 'CREATE_MODERATION_ACTION' + _PENDING
export const FETCH_GRAPHQL = 'FETCH_GRAPHQL'
export const FETCH_MODERATION_ACTIONS = 'FETCH_MODERATION_ACTIONS'
export const FETCH_MODERATION_ACTIONS_PENDING = FETCH_MODERATION_ACTIONS + _PENDING
export const FETCH_TOPICS_FOR_GROUP_ID = 'FETCH_TOPICS_FOR_GROUP_ID'
export const LOGIN = 'LOGIN'
export const LOGIN_BY_JWT = 'LOGIN_BY_JWT'
export const LOGIN_BY_TOKEN = 'LOGIN_BY_TOKEN'
export const LOGOUT = 'LOGOUT'
export const REMOVE_MODERATOR = 'REMOVE_MODERATOR'
export const REMOVE_MODERATOR_PENDING = REMOVE_MODERATOR + _PENDING
export const REMOVE_PROPOSAL_VOTE = 'REMOVE_PROPOSAL_VOTE'
export const REMOVE_PROPOSAL_VOTE_PENDING = 'REMOVE_PROPOSAL_VOTE' + _PENDING
export const RESET_STORE = 'RESET_STORE'

export const SET_CURRENT_GROUP_SLUG = 'SET_CURRENT_GROUP_SLUG'
export const SET_INITIAL_URL = 'SET_INITIAL_URL'
export const SET_RETURN_TO_ON_AUTH_PATH = 'SET_RETURN_TO_ON_AUTH_PATH'
export const SET_STATE = 'SET_STATE'

export const SWAP_PROPOSAL_VOTE = 'SWAP_PROPOSAL_VOTE'
export const SWAP_PROPOSAL_VOTE_PENDING = 'SWAP_PROPOSAL_VOTE' + _PENDING

export const TRACK_ANALYTICS_EVENT = 'TRACK_ANALYTICS_EVENT'

export const UPLOAD = 'UPLOAD'
