export const _PENDING = '_PENDING'
export const LOGIN_BY_JWT = 'LOGIN_BY_JWT'
export const LOGIN_BY_TOKEN = 'LOGIN_BY_TOKEN'
export const LOGOUT = 'LOGOUT'
export const RESET_STORE = 'RESET_STORE'
export const SET_STATE = 'SET_STATE'
export const UPLOAD = 'UPLOAD'
