export const _PENDING = '_PENDING'
export const ACCEPT_GROUP_RELATIONSHIP_INVITE = 'ACCEPT_GROUP_RELATIONSHIP_INVITE'
export const ADD_USER_TYPING = 'ADD_USER_TYPING'
export const ADD_PROPOSAL_VOTE = 'ADD_PROPOSAL_VOTE'
export const ADD_PROPOSAL_VOTE_PENDING = 'ADD_PROPOSAL_VOTE' + _PENDING
export const BLOCK_USER = 'BLOCK_USER'
export const CANCEL_GROUP_RELATIONSHIP_INVITE = 'CANCEL_GROUP_RELATIONSHIP_INVITE'
export const CHECK_INVITATION = 'CHECK_INVITATION'
export const CLEAR_USER_TYPING = 'CLEAR_USER_TYPING'
export const CLEAR_MODERATOR_SUGGESTIONS = 'CLEAR_MODERATOR_SUGGESTIONS'
export const CLEAR_MODERATION_ACTION = 'CLEAR_MODERATION_ACTION'
export const CLEAR_MODERATION_ACTION_PENDING = 'CLEAR_MODERATION_ACTION' + _PENDING
export const CREATE_GROUP = 'CREATE_GROUP'
export const CREATE_GROUP_PENDING = 'CREATE_GROUP' + _PENDING
export const CREATE_MODERATION_ACTION = 'CREATE_MODERATION_ACTION'
export const CREATE_MODERATION_ACTION_PENDING = 'CREATE_MODERATION_ACTION' + _PENDING
export const DECLINE_GROUP_INVITE = 'DECLINE_GROUP_INVITE'
export const DECLINE_JOIN_REQUEST = 'DECLINE_JOIN_REQUEST'
export const DELETE_GROUP_RELATIONSHIP = 'DELETE_GROUP_RELATIONSHIP'
export const DELETE_GROUP_RELATIONSHIP_PENDING = DELETE_GROUP_RELATIONSHIP + _PENDING
export const FETCH_GRAPHQL = 'FETCH_GRAPHQL'
export const FETCH_MODERATION_ACTIONS = 'FETCH_MODERATION_ACTIONS'
export const FETCH_MODERATION_ACTIONS_PENDING = FETCH_MODERATION_ACTIONS + _PENDING
export const FETCH_TOPICS_FOR_GROUP_ID = 'FETCH_TOPICS_FOR_GROUP_ID'
export const INVITE_CHILD_TO_JOIN_PARENT_GROUP = 'INVITE_CHILD_TO_JOIN_PARENT_GROUP'
export const INVITE_CHILD_TO_JOIN_PARENT_GROUP_PENDING = INVITE_CHILD_TO_JOIN_PARENT_GROUP + _PENDING
export const JOIN_GROUP = 'JOIN_GROUP'
export const JOIN_GROUP_PENDING = 'JOIN_GROUP_PENDING'
export const LOGIN = 'LOGIN'
export const LOGIN_BY_JWT = 'LOGIN_BY_JWT'
export const LOGIN_BY_TOKEN = 'LOGIN_BY_TOKEN'
export const LOGOUT = 'LOGOUT'
export const LOGOUT_PENDING = 'LOGOUT_PENDING'
export const LOG_ERROR = 'LOG_ERROR'
export const REGISTER = 'REGISTER'
export const REJECT_GROUP_RELATIONSHIP_INVITE = 'REJECT_GROUP_RELATIONSHIP_INVITE'
export const REMOVE_MODERATOR = 'REMOVE_MODERATOR'
export const REMOVE_MODERATOR_PENDING = REMOVE_MODERATOR + _PENDING
export const REMOVE_PROPOSAL_VOTE = 'REMOVE_PROPOSAL_VOTE'
export const REMOVE_PROPOSAL_VOTE_PENDING = 'REMOVE_PROPOSAL_VOTE' + _PENDING
export const REQUEST_FOR_CHILD_TO_JOIN_PARENT_GROUP = 'REQUEST_FOR_CHILD_TO_JOIN_PARENT_GROUP'
export const REQUEST_FOR_CHILD_TO_JOIN_PARENT_GROUP_PENDING = REQUEST_FOR_CHILD_TO_JOIN_PARENT_GROUP + _PENDING
export const RESET_STORE = 'RESET_STORE'

export const RESP_ADD_MEMBERS = 'Add Members'
export const RESP_ADMINISTRATION = 'Administration'
export const RESP_MANAGE_CONTENT = 'Manage Content'
export const RESP_REMOVE_MEMBERS = 'Remove Members'

export const SEND_EMAIL_VERIFICATION = 'SEND_EMAIL_VERIFICATION'
export const SEND_PASSWORD_RESET = 'SEND_PASSWORD_RESET'
export const SET_CURRENT_GROUP_SLUG = 'SET_CURRENT_GROUP_SLUG'
export const SET_INITIAL_URL = 'SET_INITIAL_URL'
export const SET_RETURN_TO_PATH = 'SET_RETURN_TO_PATH'
export const SET_RETURN_TO_ON_AUTH_PATH = 'SET_RETURN_TO_ON_AUTH_PATH'
export const SIGNUP = 'SIGNUP'
export const SET_STATE = 'SET_STATE'

export const SWAP_PROPOSAL_VOTE = 'SWAP_PROPOSAL_VOTE'
export const SWAP_PROPOSAL_VOTE_PENDING = 'SWAP_PROPOSAL_VOTE' + _PENDING

export const TRACK_ANALYTICS_EVENT = 'TRACK_ANALYTICS_EVENT'

export const UPLOAD = 'UPLOAD'

export const VERIFY_EMAIL = 'VERIFY_EMAIL'
