exports.up = async function (knex) {
  await knex.schema.dropTableIfExists('stripe_alert_logs')
  await knex.schema.dropTableIfExists('stripe_disputes')
  await knex.schema.dropTableIfExists('stripe_refunds')

  await knex.schema.createTable('stripe_logs', function (table) {
    table.bigIncrements('id').primary()
    table.bigInteger('stripe_account_id').unsigned().nullable()
      .references('id').inTable('stripe_accounts').onDelete('SET NULL')
    table.bigInteger('group_id').unsigned().nullable()
      .references('id').inTable('groups').onDelete('SET NULL')
    table.bigInteger('content_access_id').unsigned().nullable()
      .references('id').inTable('content_access').onDelete('SET NULL')
    table.string('log_type', 32).notNullable().comment('refund, dispute, alert')
    table.string('external_id', 255).nullable().comment('charge id for refunds, dispute id for disputes')
    table.string('alert_type', 64).nullable().comment('dispute_rate_warning, dispute_rate_critical, dispute_spike')
    table.text('threshold_triggered').nullable()
    table.string('charge_id', 255).nullable()
    table.integer('amount').nullable().comment('Amount in smallest currency unit (e.g. cents)')
    table.string('currency', 3).nullable()
    table.string('reason', 255).nullable()
    table.string('status', 64).nullable()
    table.jsonb('metadata').notNullable().defaultTo('{}')
    table.timestamps(true, true)

    table.unique(['log_type', 'external_id'])
    table.index(['group_id', 'log_type'])
    table.index(['group_id', 'alert_type'])
    table.index(['created_at'])
  })
}

exports.down = async function (knex) {
  await knex.schema.dropTableIfExists('stripe_logs')

  await knex.schema.createTable('stripe_refunds', function (table) {
    table.bigIncrements('id').primary()
    table.bigInteger('stripe_account_id').unsigned().notNullable()
      .references('id').inTable('stripe_accounts').onDelete('CASCADE')
    table.bigInteger('group_id').unsigned().notNullable()
      .references('id').inTable('groups').onDelete('CASCADE')
    table.bigInteger('content_access_id').unsigned().nullable()
      .references('id').inTable('content_access').onDelete('SET NULL')
    table.string('charge_id', 255).notNullable().unique()
    table.integer('amount').notNullable()
    table.string('currency', 3).notNullable().defaultTo('usd')
    table.string('reason', 255).nullable()
    table.timestamp('refunded_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
    table.timestamps(true, true)
  })

  await knex.schema.createTable('stripe_disputes', function (table) {
    table.bigIncrements('id').primary()
    table.bigInteger('stripe_account_id').unsigned().notNullable()
      .references('id').inTable('stripe_accounts').onDelete('CASCADE')
    table.bigInteger('group_id').unsigned().notNullable()
      .references('id').inTable('groups').onDelete('CASCADE')
    table.string('stripe_dispute_id', 255).notNullable().unique()
    table.string('charge_id', 255).notNullable()
    table.integer('amount').notNullable()
    table.string('currency', 3).notNullable().defaultTo('usd')
    table.string('reason', 255).nullable()
    table.string('status', 64).notNullable()
    table.timestamps(true, true)
  })

  await knex.schema.createTable('stripe_alert_logs', function (table) {
    table.bigIncrements('id').primary()
    table.bigInteger('group_id').unsigned().notNullable()
      .references('id').inTable('groups').onDelete('CASCADE')
    table.string('alert_type', 64).notNullable()
    table.text('threshold_triggered').notNullable()
    table.integer('dispute_count_90d').nullable()
    table.integer('refund_count_90d').nullable()
    table.integer('dispute_count_7d').nullable()
    table.integer('total_charges_90d').nullable()
    table.decimal('dispute_rate_90d', 8, 4).nullable()
    table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
  })
}
